name: test_harness
description: A simple command-line application.
version: "0.0.1"

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  # Dart
  empty_petstore_darthttp_sdk:
    path: ../generated/darthttp/empty-petstore
  simple_petstore_darthttp_sdk:
    path: ../generated/darthttp/simple-petstore
  expanded_petstore_darthttp_sdk:
    path: ../generated/darthttp/expanded-petstore

  # DIO
  empty_petstore_dio_sdk:
    path: ../generated/dio/empty-petstore
  simple_petstore_dio_sdk:
    path: ../generated/dio/simple-petstore
  expanded_petstore_dio_sdk:
    path: ../generated/dio/expanded-petstore

  # Jaguar
  empty_petstore_jaguar_sdk:
    path: ../generated/jaguar/empty-petstore
  simple_petstore_jaguar_sdk:
    path: ../generated/jaguar/simple-petstore
  expanded_petstore_jaguar_sdk:
    path: ../generated/jaguar/expanded-petstore

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
